### ISSUE TITLE
Packaged version in PyPi does not work.

### ISSUE THREAD

**Issue by sgoblin** [seppo0010/rlite-py#2] opened 2015-03-26 04:06 UTC
I believe that it has an old version of rlite, and depends on a newer version.
On my AMD64 Ubuntu machine, it fails with error:

```
vendor/rlite/src/scripting.c:37:17: fatal error: lua.h: No such file or directory
#include <lua.h>
```

It does work correctly when building from the source on GitHub.

**Comment by seppo0010** [comment] 2015-03-26 04:56
Interesting. It works on OS X, and the tag 0.0.1.4 actually builds OK on Ubuntu. I'm not sure what the problem is.

**Comment by seppo0010** [comment] 2015-03-26 05:12
Thanks for the report, the manifest file was not including the header for the lua files, fixed in 0.0.1.5 and uploaded to pypi.

**Closed as completed by seppo0010** 2015-03-26 05:12 UTC
